version: "2"

run:
  timeout: 4m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint

formatters:
  enable:
    - gofmt
    - goimports